// Generated by CoffeeScript 1.4.0
(function() {

  window.append_backbone_modal = function(backbone_class, data, container_id) {
    var modal_view;
    modal_view = new backbone_class(data);
    $("#" + container_id).html('');
    return $(modal_view.el).appendTo("#" + container_id);
  };

  window.show_error_view = function(error_heading, error_msg, div_id) {
    var data, view;
    data = {
      error_heading: error_heading,
      error_msg: error_msg
    };
    view = new GenericErrorView(data);
    $("#" + div_id).html('');
    return $(view.el).appendTo("#" + div_id);
  };

}).call(this);
